stages:
  get_data:
    cmd: python src/get_data.py data/train.txt data/test.txt data/val.txt
    deps:
    - src/get_data.py
    outs:
    - output/raw_x_test.joblib
    - output/raw_x_train.joblib
    - output/raw_x_val.joblib
    - output/raw_y_test.joblib
    - output/raw_y_train.joblib
    - output/raw_y_val.joblib
    
  preprocess:
    cmd: python src/process_data.py
    deps:
    - src/process_data.py
    - output/raw_x_test.joblib
    - output/raw_x_train.joblib
    - output/raw_x_val.joblib
    - output/raw_y_test.joblib
    - output/raw_y_train.joblib
    - output/raw_y_val.joblib

    outs:
    - output/char_index.joblib
    - output/x_train.joblib
    - output/x_test.joblib
    - output/x_val.joblib
    - output/y_test.joblib
    - output/y_train.joblib
    - output/y_val.joblib
   
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - src/process_data.py
    - src/model.py
    - output/x_train.joblib
    - output/x_val.joblib
    - output/y_train.joblib

    - output/y_val.joblib
    outs:
    - output/model.joblib
    metrics:
    - output/metrics.json

  mutamorphic_data:
    cmd: python tests/gen_mutamorphic_data.py
    deps:
    - tests/gen_mutamorphic_data.py
    - tests/testdata/URL_dataset.csv
    outs:
    - tests/mutamorphic_urls.txt
  
  mutamorphic_test:
    cmd: python -m pytest tests/test_mutamorphic.py
    deps:
    - tests/test_mutamorphic.py
    - tests/gen_mutamorphic_data.py
    - tests/testdata/mutamorphic_urls.txt
    

