name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install uv
      run: pipx install uv
    - name: Activate virtualenv
      run: |
        uv venv
        . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        uv pip sync requirements.txt
        pytest

