name: linters
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies for pylint
      run: | 
        python -m pip install --upgrade pip
        pip install pylint==2.17
        pip install black
    - name: Analysing the code with pylint, score should be 10
      run: |
        pylint src/ --fail-under=10.0
    - name: Black formatting
      run: |
        black --check src/
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1